# 服务端口配置
servers:
    port: ':80'

# mysql 配置
mysql:
    host: 'sh-cynosdbmysql-grp-q87hvhhs.sql.tencentcdb.com'
    port: 26019
    username: 'root'
    password: 'zxgf8bTa'
    database: 'boyyang'
    timeout: '10s'

# 腾讯云对象存储
cloudBase:
    clientUrl: 'https://7072-prod-2g489qm8208c3cfd-1301921121.cos.ap-shanghai.myqcloud.com'
    clientSecretID: 'AKIDQhmCQPDn9HAvTpxqdDk6JJ5cuxmMhohR'
    clientSecretKey: 'Xv4vb3IK9k8KJ4kCSVMzOZXHm48E8oKf'

# email 发送配置
email:
    from: '1761617270@qq.com'
    smtpKey: 'nqhwetnrlyxxdedi'
