# 服务配置
servers:
    host: 'http://localhost'
    port: ':80'

# mysql 配置
mysql:
    host: 'sh-cynosdbmysql-grp-q87hvhhs.sql.tencentcdb.com'
    port: 26019
    username: 'root'
    password: 'zxgf8bTa'
    database: 'boyyang'

# 腾讯云对象存储
cloudBase:
    clientUrl: 'https://7072-prod-2g489qm8208c3cfd-1301921121.cos.ap-shanghai.myqcloud.com'
    clientSecretID: 'AKIDb3GDuMYT7UaPxDDwNXQ2B5j6C1Zrsd7K'
    clientSecretKey: 'xd3C4f04rNcbKmxrVszoSpvkIZZIjtmO'

# email 发送配置
email:
    from: '1761617270@qq.com'
    smtpKey: 'nqhwetnrlyxxdedi'
